### ISSUE TITLE
Review Request for return of TSIdentifiers return

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/FIRO_TSEnsembles#21]
https://github.com/HydrologicEngineeringCenter/FIRO_TSEnsembles/blob/dc219fa312d315d9d2d54fdca4f59a09dafa34b1/src/main/java/hec/ensemble/JdbcEnsembleTimeSeriesDatabase.java#L351

**Comment by HenryGeorgist** [comment]
2020-02-19 08:27:47.195 -0500 SEVERE: (ForecastGeneratorAlternative.java:181) null
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lhec.ensemble.TimeSeriesIdentifier;
	at hec.ensemble.JdbcEnsembleTimeSeriesDatabase.getTimeSeriesIDs(JdbcEnsembleTimeSeriesDatabase.java:351)
	at forecastGenerator.ForecastGeneratorAlternative.compute(ForecastGeneratorAlternative.java:173)
	at forecastGenerator.ForecastGeneratorPlugin.compute(ForecastGeneratorPlugin.java:105)
	at hec2.wat.model.WatSimulation.computeModel(WatSimulation.java:140)
	at hec2.wat.model.WatSimulation.computeRealization(WatSimulation.java:1467)
	at hec2.wat.model.FrmSimulation.computeRealization(FrmSimulation.java:1022)
	at hec2.wat.model.FrmSimulation.computeRealizations(FrmSimulation.java:1209)
	at hec2.wat.model.WatSimulation.compute2(WatSimulation.java:1277)
	at hec2.wat.model.FrmSimOptions.compute(FrmSimOptions.java:2)
	at hec2.wat.plugin.simulationcompute.SingleThreadedSequentialEngine.computeRealizations(SingleThreadedSequentialEngine.java:62)
	at hec2.wat.model.WatSimulation.compute(WatSimulation.java:815)
	at hec2.wat.editors.WatComputeProgressDialog$WatComputeProgressPanel$2.run(WatComputeProgressDialog.java:16)
	at java.lang.Thread.run(Unknown Source)

**Comment by HenryGeorgist** [comment]
This works based on the most recent library.
