### ISSUE TITLE
new exception on constructor of JdbcTimeSeriesDatabase

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/FIRO_TSEnsembles#25]
2020-02-21 19:52:26.750 -0500 SEVERE: (ForecastGeneratorAlternative.java:206) null
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: table_types)
	at org.sqlite.core.DB.newSQLException(DB.java:941)
	at org.sqlite.core.DB.newSQLException(DB.java:953)
	at org.sqlite.core.DB.throwex(DB.java:918)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
	at org.sqlite.core.DB.prepare(DB.java:257)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:47)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
	at hec.JdbcTimeSeriesDatabase.<init>(JdbcTimeSeriesDatabase.java:64)
	at forecastGenerator.ForecastGeneratorAlternative.compute(ForecastGeneratorAlternative.java:188)
	at forecastGenerator.ForecastGeneratorPlugin.compute(ForecastGeneratorPlugin.java:117)
	at hec2.wat.model.WatSimulation.computeModel(WatSimulation.java:140)
	at hec2.wat.model.WatSimulation.computeRealization(WatSimulation.java:1467)
	at hec2.wat.model.FrmSimulation.computeRealization(FrmSimulation.java:1022)
	at hec2.wat.model.FrmSimulation.computeRealizations(FrmSimulation.java:1209)
	at hec2.wat.model.WatSimulation.compute2(WatSimulation.java:1277)
	at hec2.wat.model.FrmSimOptions.compute(FrmSimOptions.java:2)
	at hec2.wat.plugin.simulationcompute.SingleThreadedSequentialEngine.computeRealizations(SingleThreadedSequentialEngine.java:62)
	at hec2.wat.model.WatSimulation.compute(WatSimulation.java:815)
	at hec2.wat.editors.WatComputeProgressDialog$WatComputeProgressPanel$2.run(WatComputeProgressDialog.java:16)
	at java.lang.Thread.run(Unknown Source)

**Comment by HenryGeorgist** [comment]
I suspect this is because my old file does not meet the new schema. I need a new file if that is the case.

**Comment by ktarbet** [comment]
making a SQL update script may be a good solution

**Comment by HenryGeorgist** [comment]
@ktarbet I think that is a good idea - or add logic to create the table if it is not present.

I am curious if we are not being careful enough with our constructors. It seems we are doing actions that yield exceptions quite frequently. is that a good choice?

**Comment by MikeNeilson** [comment]
Certain at this phase no, better to throw errors quickly and let the user figure out what to do that get to far and corrupt their particular database. Plus one of the main points of exceptions is that you can throw them from a constructor when initialization files.

I link the idea of an update script, we would also need to add a version, then we can create something similar to how it's done on android. However, I am always weary of removing meaningful control from the user. Perhaps now is the time to change the create -> true/false flag to an int with the following options and some extra logic: (names of course open to debate)

CREATE_NEW
OPEN_EXISTING
UPDATE
NOUPDATE

And the way that gets used:
ex
CREATE_NEW | OPEN_EXISTING|NOUPDATE 
you get a well defined exception like "DatabaseFileOutofDate version = X library expects version 7 can update without breaking compatibiliy" if the database exists already and is behind
CREATE_NEW_|OPEN_EXISTING|UPDATE
will just update the database.
OPEN_EXISTING|NO_UPDATE
expects the database to exist already 

The 3rd one would likely be used in processing scripts with the first two being more likely for something like WATs initial processing.

Anyways, food for thought. What do y'all think?

**Comment by HenryGeorgist** [comment]
I like it. I am a fan of the enum idea. Let me know what you need from me (if anything) to get this underway.

**Comment by HenryGeorgist** [comment]
I think you need to make it a byte flag, because you will have to have combined states. I think java enums have this capability built in, but you get the idea. Maybe that is what you mean with your pipes.

**Comment by ktarbet** [comment]
To get past the error you can try this:  (backup database first!)
C:\sqlite-tools-win32-x86-3310100>sqlite3 ensemble.db
 sqlite> .read database.sql
 

download exe here:  https://www.sqlite.org/2020/sqlite-tools-win32-x86-3310100.zip

**Comment by ktarbet** [comment]
Another solution to the constructor confusion would be a static method to create a database, and make creation a separate task,  then the constructor can be for opening.

**Comment by HenryGeorgist** [comment]
I was thinking about that as a design decision as well @ktarbet.

**Comment by MikeNeilson** [comment]
The question there is: should opening/initializing a resource be a two step operation? My vote on that is no. The creation/updating of the file is the responsibility of the database object. Separating the initialization from the constructor (and really think about that part of the sentence for a minute) turns it into a user responsibility; the least reliable component of any operation. 

The users only responsibility should be to guide the object in what happens.

**Comment by HenryGeorgist** [comment]
Given that argument, we need to modify the current constructor arguments to reflect an enumeration, build an enum, and implement the constructor to take the appropriate actions.

**Comment by MikeNeilson** [comment]
I'll try to find some time to work on that Monday, if you could upload your current file into the test resource, assuming it isn't too big, that will be useful for testing the upgrade scripts.

**Comment by HenryGeorgist** [comment]
For this item, I will only be tracking the exception (which may be primarily my action) - all other work will get issued in new tickets.

The database is 8gb. not conducive for testing.

**Comment by HenryGeorgist** [comment]
> To get past the error you can try this: (backup database first!)
> C:\sqlite-tools-win32-x86-3310100>sqlite3 ensemble.db
> sqlite> .read database.sql

@ktarbet do I need to do more than .read? shouldn't there be an update statement or something? This did not work.

**Comment by HenryGeorgist** [comment]
i got it to work. it was a \ / issue, i needed to specify the paths with forward slashes
