### ISSUE TITLE
null pointer in write method

### ISSUE THREAD

**Issue by HenryGeorgist** [HydrologicEngineeringCenter/FIRO_TSEnsembles#32]
https://github.com/HydrologicEngineeringCenter/FIRO_TSEnsembles/blob/142f3ddbc38765098656a3e2483398a5990ce4ca/src/main/java/hec/JdbcTimeSeriesDatabase.java#L94

java.lang.NullPointerException
	at hec.JdbcTimeSeriesDatabase.write(JdbcTimeSeriesDatabase.java:94)
	at forecastGenerator.ForecastGeneratorAlternative.compute(ForecastGeneratorAlternative.java:212)
	at forecastGenerator.ForecastGeneratorPlugin.compute(ForecastGeneratorPlugin.java:117)
	at hec2.wat.model.WatSimulation.computeModel(WatSimulation.java:140)
	at hec2.wat.model.WatSimulation.computeRealization(WatSimulation.java:1467)
	at hec2.wat.model.FrmSimulation.computeRealization(FrmSimulation.java:1022)
	at hec2.wat.model.FrmSimulation.computeRealizations(FrmSimulation.java:1209)
	at hec2.wat.model.WatSimulation.compute2(WatSimulation.java:1277)
	at hec2.wat.model.FrmSimOptions.compute(FrmSimOptions.java:2)
	at hec2.wat.plugin.simulationcompute.SingleThreadedSequentialEngine.computeRealizations(SingleThreadedSequentialEngine.java:62)
	at hec2.wat.model.WatSimulation.compute(WatSimulation.java:815)
	at hec2.wat.editors.WatComputeProgressDialog$WatComputeProgressPanel$2.run(WatComputeProgressDialog.java:16)
	at java.lang.Thread.run(Unknown Source)

**Comment by HenryGeorgist** [comment]
I believe the issue is that you are getting the ensemble member referencing the issue date from the issue dates with no tolerance. It seems the return is null. I suggest we should ensure that it is simple to iterate through the ensembles across time. Currently it is not. The use case Joan was working through where a specific time is requested is in need of review.

**Comment by ktarbet** [comment]
I've stared a branch feature/iterator 
here are proposed goals for this branch:

- [ ] Fix this issue (issue #32)
- [ ]  improve the ability to iterate over time
- [ ] eliminate the tolerance argument and update ResSim Script to match

**Comment by HenryGeorgist** [comment]
@ktarbet can we create separate issues for each goal and tag them with a milestone associated with the branch name?
The ForecastGenerator plugin will be creating a database file next to the lifecycle level dss file. 

We should talk about what you are hoping to do with the hard coded input sqlite database file (it currently is specified in an alternative config file and isn't "hard coded" in the plugin.

**Comment by ktarbet** [comment]
@HenryGeorgist  I have reproduced the error for this issue.  It was the getEnsemble(t) method call without tolerance.  I'll be pushing a fix and Junit test.

**Comment by ktarbet** [comment]
I'm having this issue when generating test data for ResSim.

**Comment by ktarbet** [comment]
EnsembleTimeSeries.getIssueDates() needs some help, I'm working on that.

**Comment by ktarbet** [comment]
EnsembleTimeSeries is confused because it is used as both an iterator and collection of ensembles. 

EnsembleTimeSeries.getIssueDates() doesn't know whether to read from disk, or from memory.

I propose we remove the database from EnsembleTimeSeries, and make a EnsembleTimeSeriesReader.


-- TimeSeriesDatabase --
```
// read whole EnsembleTimeSeries into memory
public abstract EnsembleTimeSeries getEnsembleTimeSeries(TimeSeriesIdentifier timeseriesID);
// get a database iterator (new class EnsembleTimeSeriesReader )
public abstract EnsembleTimeSeriesReader getEnsembleTimeSeriesReader(TimeSeriesIdentifier timeseriesID);
```

@HenryGeorgist  @MikeNeilson  -- What are your thoughts?

**Comment by HenryGeorgist** [comment]
@ktarbet i agree.
